"""add note owners

Revision ID: c6131cd7b65c
Revises: 76c64299810c
Create Date: 2026-09-18 19:54:27.372088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6131cd7b65c'
down_revision: Union[str, Sequence[str], None] = '76c64299810c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_telegram_user_id'), 'owners', ['telegram_user_id'], unique=True)
    op.add_column('notes', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.execute(
        sa.text(
            """
            INSERT INTO owners (telegram_user_id)
            SELECT 0
            WHERE EXISTS (SELECT 1 FROM notes)
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE notes
            SET owner_id = (
                SELECT id
                FROM owners
                WHERE telegram_user_id = 0
            )
            WHERE owner_id IS NULL
            """
        )
    )
    op.alter_column('notes', 'owner_id', nullable=False)
    op.create_index(op.f('ix_notes_owner_id'), 'notes', ['owner_id'], unique=False)
    op.create_foreign_key('fk_notes_owner_id_owners', 'notes', 'owners', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notes_owner_id_owners', 'notes', type_='foreignkey')
    op.drop_index(op.f('ix_notes_owner_id'), table_name='notes')
    op.drop_column('notes', 'owner_id')
    op.drop_index(op.f('ix_owners_telegram_user_id'), table_name='owners')
    op.drop_table('owners')
    # ### end Alembic commands ###
